apiVersion: apps/v1
kind: Deployment
metadata:
  name: stock-web
  namespace: stock
  labels:
    app: stock-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: stock-web
  template:
    metadata:
      